name: Build OpenWrt for AX5400

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Free Disk Space
      run: |
        sudo rm -rf /usr/share/dotnet /usr/local/lib/android /opt/ghc
        sudo apt-get clean

    - name: Initialization environment
      env:
        DEBIAN_FRONTEND: noninteractive
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential clang flex bison gstreamer1.0-plugins-base \
        gettext libssl-dev libncurses5-dev libncursesw5-dev zlib1g-dev python3 \
        python3-pip python3-ply python3-pyelftools git rsync unzip libglib2.0-dev libltdl-dev wget file time

    - name: Clone source code
      run: |
        git clone -b openwrt-24.10 https://github.com/immortalwrt/immortalwrt openwrt
        cd openwrt
        ./scripts/feeds update -a
        ./scripts/feeds install -a

    - name: Generate configuration
      run: |
        cd openwrt
        echo "CONFIG_TARGET_qualcommax=y" > .config
        echo "CONFIG_TARGET_qualcommax_ipq50xx=y" >> .config
        echo "CONFIG_TARGET_DEVICE_qualcommax_ipq50xx_DEVICE_xiaomi_redmi-ax5400=y" >> .config
        echo "CONFIG_TARGET_DEVICE_PACKAGES_qualcommax_ipq50xx_DEVICE_xiaomi_redmi-ax5400=y" >> .config
        
        # Обязательные модули ядра и зависимости для Подкопа
        echo "CONFIG_PACKAGE_kmod-nft-tproxy=y" >> .config
        echo "CONFIG_PACKAGE_kmod-inet-diag=y" >> .config
        echo "CONFIG_PACKAGE_kmod-tun=y" >> .config
        echo "CONFIG_PACKAGE_sing-box=y" >> .config
        echo "CONFIG_PACKAGE_curl=y" >> .config
        echo "CONFIG_PACKAGE_bind-dig=y" >> .config
        echo "CONFIG_PACKAGE_coreutils-base64=y" >> .config
        echo "CONFIG_PACKAGE_ca-bundle=y" >> .config
        echo "CONFIG_PACKAGE_ca-certificates=y" >> .config
        
        make defconfig

    - name: Download packages
      run: |
        cd openwrt
        make download -j8
        find dl -size -1024c -exec rm -f {} \;

    - name: Compile the firmware
      run: |
        cd openwrt
        make -j$(nproc) || make -j1 V=s

    - name: Prepare Artifacts
      run: |
        mkdir -p /tmp/out
        # Ищем ВСЕ bin файлы во всей папке bin и копируем в /tmp/out
        find openwrt/bin/ -type f -name "*.bin" -exec cp {} /tmp/out/ \;
        ls -la /tmp/out/

    - name: Upload firmware to release
      uses: actions/upload-artifact@v4
      with:
        name: Redmi_AX5400_Podkop_Firmware
        path: /tmp/out/
